2020-02-19 10:04:53,954 DEBUG   MainThread:8944 [wandb_config.py:_load_defaults():119] no defaults not found in config-defaults.yaml
2020-02-19 10:04:53,977 DEBUG   MainThread:8944 [meta.py:setup():94] code probe starting
2020-02-19 10:04:53,977 DEBUG   MainThread:8944 [meta.py:setup():98] non time limited probe of code
2020-02-19 10:04:54,004 DEBUG   MainThread:8944 [util.py:is_cygwin_git():319] Failed checking if running in CYGWIN due to: FileNotFoundError(2, 'The system cannot find the file specified', None, 2, None)
2020-02-19 10:04:54,005 DEBUG   MainThread:8944 [meta.py:_setup_code_git():49] probe for git information
2020-02-19 10:04:54,007 DEBUG   MainThread:8944 [cmd.py:execute():722] Popen(['git', 'cat-file', '--batch-check'], cwd=E:\OSM_Images_Skynet, universal_newlines=False, shell=None)
2020-02-19 10:04:54,082 DEBUG   MainThread:8944 [cmd.py:execute():722] Popen(['git', 'rev-parse', '--show-toplevel'], cwd=E:\OSM_Images_Skynet, universal_newlines=False, shell=None)
2020-02-19 10:04:54,160 DEBUG   MainThread:8944 [meta.py:_setup_code_program():58] scan for untracked program
2020-02-19 10:04:54,161 DEBUG   MainThread:8944 [cmd.py:execute():722] Popen(['git', 'status', '--porcelain', '--untracked-files'], cwd=E:\OSM_Images_Skynet, universal_newlines=False, shell=None)
2020-02-19 10:04:54,255 DEBUG   MainThread:8944 [meta.py:setup():116] code probe done
2020-02-19 10:04:54,264 DEBUG   MainThread:8944 [run_manager.py:__init__():536] Initialized sync for osm_pseudo_raytracing/cjq74pgz
2020-02-19 10:04:54,270 INFO    MainThread:8944 [run_manager.py:wrap_existing_process():1134] wrapping existing process 19052
2020-02-19 10:04:54,272 DEBUG   MainThread:8944 [connectionpool.py:_new_conn():815] Starting new HTTPS connection (1): pypi.org:443
2020-02-19 10:04:54,339 DEBUG   MainThread:8944 [connectionpool.py:_make_request():396] https://pypi.org:443 "GET /pypi/wandb/json HTTP/1.1" 200 41171
2020-02-19 10:04:54,367 INFO    MainThread:8944 [run_manager.py:init_run():919] system metrics and metadata threads started
2020-02-19 10:04:54,367 INFO    MainThread:8944 [run_manager.py:init_run():953] upserting run before process can begin, waiting at most 10 seconds
2020-02-19 10:04:54,385 DEBUG   Thread-20 :8944 [connectionpool.py:_new_conn():815] Starting new HTTPS connection (1): api.wandb.ai:443
20202020-02-19 10:04:58,709 DEBUG   MainThread:20896 [connectionpool.py:_new_conn():815] Starting new HTTPS connection (1): api.wandb.ai:443
2020-02-19 10:04:58,960 DEBUG   MainThread:20896 [connectionpool.py:_make_request():396] https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 200 58
2020-02-19 10:05:03,971 DEBUG   MainThread:20896 [connectionpool.py:_new_conn():815] Starting new HTTPS connection (1): api.wandb.ai:443
2020-02-19 10:05:04,198 DEBUG   MainThread:20896 [connectionpool.py:_make_request():396] https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 200 58
2020-02-19 10:05:09,207 DEBUG   MainThread:20896 [connectionpool.py:_new_conn():815] Starting new HTTPS connection (1): api.wandb.ai:443
2020-02-19 10:05:09,778 DEBUG   MainThread:20896 [connectionpool.py:_make_request():396] https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 200 58
2020-02-19 10:05:14,784 DEBUG   MainThread:20896 [connectionpool.py:_new_conn():815] Starting new HTTPS connection (1): api.wandb.ai:443
2020-02-19 10:05:15,000 DEBUG   MainThread:20896 [connectionpool.py:_make_request():396] https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 200 58
2020-02-19 10:05:20,005 DEBUG   MainThread:20896 [connectionpool.py:_ne